### ISSUE TITLE
 Views

### ISSUE THREAD

**Issue by Guellaf** [medohassan2021/invoice#1]
![image](https://user-images.githubusercontent.com/47402966/105915832-70acc680-6030-11eb-9dd1-dcbdd2d1f90c.png)

**Comment by medohassan2021** [comment]
السلام عليكم ورحمة الله 
بعتذر جدا عن الخطاء الغير مقصود ده وشكرا جدا لاني مجؤبتش ارفع الملف مضغوط قبل كدا 
اكتشفت ان برنامج الضغط بيعمل مشاكل في الملفات 
اتفضل اللينك من القناة التعليمية نفسها 
Samir-Gamal/Invoices_Project



| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Samir-Gamal/Invoices_Project

Invoices_Project. Contribute to Samir-Gamal/Invoices_Project development by creating an account on GitHub.
 |

 |

 |

وبعتذر جدا
